- js/io/formats/modded_entity.js
- js/io/project.js
This adds a new forge 1.17 template to the modded entities. Mojang refactored the system quite a bit, and previous assumptions no longer work, so a few new expansion tokens / regex replacements have been added to account for this. Some simple testing shows it works on my end. More testing would be appreciated. I have published a build of this to my website which can be used for easier testing, see [https://sizableshrimp.me/blockbench/](https://sizableshrimp.me/blockbench/)
> Add support for forge 1.17 entity models

- js/io/formats/modded_entity.js
Currently, blockbench exports for modded entities do not pass the color to the model parts. This means the color values are ignored entirely. Normally, the values passed to `renderToBuffer`/`render` are all 1.0F. This is what model parts default to if color values are not passed in. However, mods can change these color values to change the color of the final rendered model. It would be nice if Blockbench respected these color options in future exports. So, it is a simple fix that is done here.
> Pass color to model parts in modded entity models on 1.15+

- js/file_system.js
Fixes #1485.
In desktop mode, Blockbench would only add a valid file extension if `pathToExtension` couldn't find an extension. 
In web mode, Blockbench would only add a valid file extension if the file name ended with the first extension in the `options.extensions` array.
When exporting a file, Blockbench will now add a valid extension if it is missing one.
> Check for a valid file extension when exporting

- js/copy_paste.js
- js/io/format.js
- js/io/formats/java_block.js
- js/modeling/transform.js
I'm currently working on a Minecraft mod that adds in a custom json model format. It's essentially an extension of the default vanilla format and it removes the 22.5 step limitation, however it keeps the axis restriction. I am also creating a plugin so models can be designed with the new format, unfortunately I ran into a wall developing the plugin where it's pretty much impossible for me to remove the step limitation for my format. I've tried patching and tons of other work arounds but there was always new bugs introduced doing so.
Hence why this PR is being created. I've kept changes to a minimum and ensured existing formats don't break.
> Model formats can now disable cube rotation snapping

- js/io/project.js
This event might make sense to have in core. I've originally implemented it on our fork to update the unsaved file indicator within bridge.'s own UI to accurately reflect Blockbench's internal state.
Feel free to close if you don't think it's a good fit.
> feat: saved state changed event

- js/interface/menu_bar.js
This PR fixes the behaviour when clicking on an selected menu bar item (e.g. File). Currently nothing happens when you click the item, which seems to be unintentionally, because there already is code in place to hide the menu, after clicking on it. Sadly the code is not working due to an if statement which won't become true. I've simply removed it (not sure if it is important, then simply close this PR, but maybe there is another way to fix this).
Tested on web (mobileand desktop) and desktop.
> Fix: Menu won't close after deselecting it

- js/io/formats/obj.js
There is a trailing space in the map_Kd property of an mtl file that prevents some software from reading textures correctly.
> Remove trailing space from map_Kd property

- js/interface/actions.js
- js/modeling/transform_gizmo.js
- lang/en.json
This PR extends the transform gizmo functionality to support modifying a cube's stretch values. A corresponding tool was also added (default shortcut of `alt + s` to match scale which is just `s`). Probably not the best icon for it but I didn't see a better one in font awesome's collection.
> Added tool and gizmo for stretching

- js/io/formats/modded_entity.js
This PR adds the template for the Yarn mappings for the modded entity export animation system (just the template, not the UI of picking the mapping)
> Add Yarn Mapping Export Template for Keyframe Animations

- js/io/formats/gltf.js
Got an error on export on this line, likely copied from the mesh.js code. 
In this context the equivalent element is the child, this removes the error and results in a white-colored material for the exported, non-textured file.
> GLTF Export Bug : element not defined

- js/io/formats/fbx.js
This PR is a start at fixing binary FBX exporting. With this PR, geometry exporting and texturing exporting of an external file should work. What's still broken is exporting textures created in BlockBench (and not exported externally), aka embedded textures, and exporting animations.
If someone wants to debug this further: exporting embedded textures causes Blender to throw the error "IMB_ibImageFromMemory: unknown file-format (<packed data>)". Exporting animations leaves the keyframe vales with nan values.
> Fix binary FBX export geometry & external texture exporting

- main.js
This PR allows advanced users to specify a custom `userData` directory.
Very useful for truly portable installations, and setting up development environments.
> Add a CLI argument to specify the userData folder.

- js/outliner/cube.js
- js/outliner/mesh.js
- js/outliner/texture_mesh.js
- js/preview/canvas.js
- js/preview/preview.js
- lang/en.json
- lang/fr.json
- package-lock.json
This pull request adds the view mode requested in #2316 
At the moment localization seems to not be working (on my end only ?), even tho I have added entries in the lang files of which I speak the language, I haven't managed to find why.
What I did here is basically duplicate the "solid" view mode and its associated canvas & preview setup, but with an added marker color component, just like the default "texture" view mode already has
Demo Video (recorded on the netify preview to have working localization)
https://github.com/JannisX11/blockbench/assets/30528331/bd0afeed-e299-4e0b-af7f-1a69707d3933
> Added "solid with marker color" view mode from #2316

- js/interface/menu_bar.js
- js/io/formats/bbmodel.js
- js/io/project.js
- lang/en.json
This PR adds incremental saving, similar to what can be seen in Blender and Autodesk Maya.
https://github.com/JannisX11/blockbench/assets/30528331/49b4f6c7-6054-457f-9d94-ad2136febdd4
This would be useful to keep past versions of a given project file, without having to set up boilerplate version control tools like Git.
Would close #2360
> Added Incremental Saving

- js/animations/molang.js
- Added suggestion a priority system for Namespaces, Queries, and RootTokens.
- Contexts that inherit other contexts can safely define "duplicate" namespaces in order to add more queries to inherited Namespaces.
> 🚧 Molang Autocomplete Enhancements

- js/interface/settings.js
- js/preview/canvas.js
- js/texturing/textures.js
- lang/en.json
This PR modifies the Textured and UV Preview vertex shaders to add the centroid qualifier to prevent UVs from getting extrapolated when using anti-aliasing.
I'm not certain but if mipmaps are ever introduced, I believe it could cause issues with trying to compute the mip levels. If this becomes an issue the simplest solution would be to pass non-centroid UVs and use those for the mip map derivatives and use the centroid UVs to prevent sampling texels outside of the triangles boundaries.
Should this anti-aliasing fix be tied to a setting or should it always be enabled?
> Fix texture bleeding when using anti-aliasing

- js/preview/preview.js
- Reverted 067ca506a60db57ecc25daf491a180c98934876e as the matrix multiplication was done too early.
- Used the ``.worldMatrix`` from the intersected object instead of its local transform ``.matrix``.
> Fixed 3D brush matrix when using groups with a rotation and translation

- js/preview/preview_scenes.js
- js/texturing/texture_groups.js
This commit ought to help with the reflections in the Material Preview. Here's what has changed:
- Added `normalScale` to flip the normal map to use right-handed (DirectX) normal maps for RenderDragon compatibility.
- Only use PMREM when a PreviewScene has been activated. 
- Now using `.texture` property for the `envMap`
- Update environment map when the material is updated. (User may have changed scene in between material updates.)
Upon initially loading a scene, the environment may appear too dark without a cubemap preset. The scene's lights will still reflect off the model without the cubemap.
Here is the reflection with a preview scene activated and the material updated.
https://github.com/user-attachments/assets/8c4524ad-eb7b-483e-867c-0e97c1cf4a87
> Fix PBR Reflections

- js/preview/preview.js
- Replaced the temporary brush outline offset fix with a proper solution that makes the brush account for every kind of scene transformation.
- Fixed issue where z-offset was not being applied anymore when working with java models.
> Fixed Java brush matrix

- js/outliner/outliner.js
Empty arrays do not evaluate to false. Fixes #2775
> Fixes #2775

- js/animations/animation_mode.js
- js/animations/molang.js
before, it was running a bunch of redundant regex per variable per line, just to find a variable's definition
e.g. (a line with `<variable>=<value>`)
since all `variableHandler` needs is the variable's `val`, we can pre-process the raw text when it changes and store that for later
otherwise, `variableHandler` is called recursively *many* times depending on how your variable placeholder text is structured.
> Performance: parse variable placeholders once on text change

- js/preview/canvas.js
This fix enables the `OES_standard_derivatives` extension when using a WebGL 1 context, but leaves WebGL 2 untouched since it is available by default then.
> Fix brush outline not showing up when using WebGL 1

- js/plugin_loader.ts
- types/custom/misc.d.ts
Opposite of current `loaded_plugin` event.
> ✨ Add event `unloaded_plugin`

- keymaps/blender.bbkeymap
I have changed line 69 of blender.bbkeymaps from null to {"key": 65, "shift": true}
> adding a keybind to the blender bbkeymap
